# utility class and functions for PDF text extraction, cleaning, and duplicate removal for BGE embedding preparation

import re
import hashlib
import pymupdf as pdf
from typing import List
from langchain_core.documents import Document


def extract_text_from_pdf(pdf_path: str, selected_pages: list[int], output_file: str) -> None:

   
    
    doc = pdf.open(pdf_path)
    with open(output_file, "wb") as out:
        for page_num in selected_pages:
            if page_num < len(doc):
                page = doc[page_num]
                text = page.get_text()
                text = " ".join(text.split()) 
                out.write(text.encode("utf8"))
                out.write(b"\n\n")
    doc.close()

    print(f"Extracted {len(selected_pages)} pages to {output_file}")


def clean_text_for_bge(text: str) -> str:
   
    text = re.sub(r'[^\x00-\x7F\u00A0-\uFFFF]', ' ', text)
    text = re.sub(r'http[s]?://[^\s]+|www\.[^\s]+', '', text)
    text = re.sub(r'page?\s*\d+\s*(of\s*)?\d+', '', text, flags=re.IGNORECASE)
    text = re.sub(r'seite?\s*\d+', '', text, flags=re.IGNORECASE)
    text = re.sub(r'©?\s*(?:great barrier reef|marine park|\d{4})', '', text, flags=re.IGNORECASE)
    text = re.sub(r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b', '', text)
    text = re.sub(r'all rights reserved', '', text, flags=re.IGNORECASE)
    text = re.sub(r'generated by adobe|document id|created with', '', text, flags=re.IGNORECASE)
    text = " ".join(text.split())
    
    return text.strip()



def get_chunk_hash(chunk_content: str) -> str:

    return hashlib.md5(chunk_content.encode()).hexdigest()


def remove_duplicate_chunks(chunks: List[Document]) -> List[Document]:

    seen = set()
    unique_chunks = []
    
    for chunk in chunks:
        content_hash = hash(chunk.page_content)
        if content_hash not in seen:
            seen.add(content_hash)
            unique_chunks.append(chunk)
    
    print(f"Removed {len(chunks) - len(unique_chunks)} duplicates. {len(unique_chunks)} chunks remain.")
    return unique_chunks

