"""
Utility functions for data pipeline processing.

Provides utilities for:
- Configuration loading from YAML
- PDF text extraction and page selection
- Text cleaning and preprocessing

- Duplicate chunk detection and removal
- Logging setup
- Document metadata handling
"""

import re
import json
import os
import yaml
import pymupdf as pdf
from typing import List, Dict, Any
from langchain_core.documents import Document
from langdetect import detect, LangDetectException
import logging

def setup_logger(name: str, level: int = logging.INFO) -> logging.Logger:

    logger = logging.getLogger(name)
    logger.setLevel(level)
    
    if not logger.handlers:
        handler = logging.StreamHandler()
        formatter = logging.Formatter(
            fmt='%(asctime)s | %(name)-20s | %(levelname)-8s | %(message)s',
            datefmt='%Y-%m-%d %H:%M:%S'
        )
        handler.setFormatter(formatter)
        logger.addHandler(handler)
    
    return logger

logger = setup_logger(__name__)

def load_config(config_path: str = "config.yaml") -> Dict[str, Any]:

    if not os.path.exists(config_path):
        project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        config_path = os.path.join(project_root, "config.yaml")
    
    with open(config_path, 'r', encoding='utf-8') as f:
        return yaml.safe_load(f)

def extract_text_from_pdf(pdf_path: str, selected_pages: List[int], output_file: str) -> None:
   
    doc = pdf.open(pdf_path)
    with open(output_file, "wb") as out:
        for page_num in selected_pages:
            if page_num < len(doc):
                page = doc[page_num]
                text = page.get_text()
                # Normalize whitespace
                text = " ".join(text.split()) 
                out.write(text.encode("utf8"))
                out.write(b"\n\n")
    doc.close()

    logger.info(f"Extracted {len(selected_pages)} pages to {output_file}")


def clean_text_for_bge(text: str) -> str:
    
    text = re.sub(r'[^\x00-\x7F\u00A0-\uFFFF]', ' ', text)
    text = re.sub(r'http[s]?://[^\s]+|www\.[^\s]+', '', text)
    text = re.sub(r'page?\s*\d+\s*(of\s*)?\d+', '', text, flags=re.IGNORECASE)
    text = re.sub(r'seite?\s*\d+', '', text, flags=re.IGNORECASE)
    text = re.sub(r'©?\s*(?:great barrier reef|marine park|\d{4})', '', text, flags=re.IGNORECASE)
    text = re.sub(r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b', '', text)
    text = re.sub(r'all rights reserved', '', text, flags=re.IGNORECASE)
    text = re.sub(r'generated by adobe|document id|created with', '', text, flags=re.IGNORECASE)
    text = " ".join(text.split())
    
    return text.strip()


def load_metadata_from_config(filename: str, config_path: str = "../data/metadata.json") -> Dict[str, Any]:
   
    default_metadata = {
        "filename": filename,  
        "source": "Unknown",   
        "title": "Unknown",
        "author": "Unknown",
        "year": None,
        "description": "Document processed for RAG",
        "categories": []  
    }
    
    config_file = os.path.join(os.path.dirname(os.path.dirname(__file__)), "data", "metadata.json")
    
    if os.path.exists(config_file):
        try:
            with open(config_file, 'r', encoding='utf-8') as f:
                config = json.load(f)
                if filename in config:
                    metadata = default_metadata.copy()
                    metadata.update(config[filename])
                    return metadata
        except Exception as e:
            logger.warning(f"Could not load metadata config: {e}")
    
    return default_metadata


def remove_duplicate_chunks(chunks: List[Document]) -> List[Document]:
    
    seen = set()
    unique_chunks = []
    
    for chunk in chunks:

        normalized_content = " ".join(chunk.page_content.lower().split())
        content_hash = get_chunk_hash(normalized_content)
        
        if content_hash not in seen:
            seen.add(content_hash)
            unique_chunks.append(chunk)
    
    logger.info(f"Removed {len(chunks) - len(unique_chunks)} duplicates. {len(unique_chunks)} chunks remain.")
    return unique_chunks


def detect_language(text: str, default_language: str = "en") -> str:
    
    if not text or len(text.strip()) < 10:
        return default_language
    
    try:
        detected_lang = detect(text[:300])
        return detected_lang
    except LangDetectException:
      
        return default_language
    except Exception as e:
        logger.warning(f"Language detection error: {e}")
        return default_language
    


