# utility class and functions for PDF text extraction, cleaning, and duplicate removal for BGE embedding preparation

import re
import hashlib
import json
import os
import yaml
import pymupdf as pdf
from typing import List, Dict, Any, Optional
from langchain_core.documents import Document
from langdetect import detect, LangDetectException
import logging


def load_config(config_path: str = "config.yaml") -> Dict[str, Any]:
    """
    Load configuration from config.yaml file.
    Falls back to defaults if config file not found.
    
    Args:
        config_path: Path to config file (relative to project root)
        
    Returns:
        Dictionary with configuration values
    """
    # Try to find config.yaml
    if not os.path.exists(config_path):
        # Try relative to project root
        project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        config_path = os.path.join(project_root, "config.yaml")
    
    if os.path.exists(config_path):
        try:
            with open(config_path, 'r', encoding='utf-8') as f:
                config = yaml.safe_load(f)
                print(f"✓ Configuration loaded from {config_path}")
                return config
        except Exception as e:
            print(f"Warning: Could not load config file: {e}")
            return _get_default_config()
    else:
        print(f"Warning: Config file not found at {config_path}. Using defaults.")
        return _get_default_config()


def _get_default_config() -> Dict[str, Any]:
    """
    Return default configuration if config.yaml is not available.
    """
    return {
        'ingestion': {
            'breakpoint_threshold_amount': 80.0,
            'breakpoint_threshold_type': 'percentile',
            'embedding_model': 'BAAI/bge-m3',
            'default_pages': [5, 87]
        },
        'embedding': {
            'model_name': 'BAAI/bge-m3',
            'embedding_dimension': 1536
        },
        'vector_store': {
            'persist_directory': 'data/vector_store',
            'index_type': 'FAISS'
        },
        'retrieval': {
            'score_threshold': 0.3,
            'top_k': 5,
            'min_chunk_length': 100
        },
        'llm': {
            'model': 'llama3',
            'temperature': 0.1,
            'top_p': 0.1,
            'max_tokens': 512
        },
        'language': {
            'default_language': 'en',
            'min_detection_length': 10
        },
        'data_exploration': {
            'top_keywords_count': 10,
            'min_word_length': 2,
            'short_document_threshold': 100
        }
    }


def extract_text_from_pdf(pdf_path: str, selected_pages: List[int], output_file: str) -> None:

   
    
    doc = pdf.open(pdf_path)
    with open(output_file, "wb") as out:
        for page_num in selected_pages:
            if page_num < len(doc):
                page = doc[page_num]
                text = page.get_text()
                text = " ".join(text.split()) 
                out.write(text.encode("utf8"))
                out.write(b"\n\n")
    doc.close()

    print(f"Extracted {len(selected_pages)} pages to {output_file}")


def clean_text_for_bge(text: str) -> str:
   
    text = re.sub(r'[^\x00-\x7F\u00A0-\uFFFF]', ' ', text)
    text = re.sub(r'http[s]?://[^\s]+|www\.[^\s]+', '', text)
    text = re.sub(r'page?\s*\d+\s*(of\s*)?\d+', '', text, flags=re.IGNORECASE)
    text = re.sub(r'seite?\s*\d+', '', text, flags=re.IGNORECASE)
    text = re.sub(r'©?\s*(?:great barrier reef|marine park|\d{4})', '', text, flags=re.IGNORECASE)
    text = re.sub(r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b', '', text)
    text = re.sub(r'all rights reserved', '', text, flags=re.IGNORECASE)
    text = re.sub(r'generated by adobe|document id|created with', '', text, flags=re.IGNORECASE)
    text = " ".join(text.split())
    
    return text.strip()



def get_chunk_hash(chunk_content: str) -> str:

    return hashlib.md5(chunk_content.encode()).hexdigest()


def load_metadata_from_config(filename: str, config_path: str = "../data/metadata.json") -> Dict[str, Any]:
   
    # Default metadata structure - all fields with sensible defaults
    default_metadata = {
        "filename": filename,  
        "source": "Unknown",   
        "title": "Unknown",
        "author": "Unknown",
        "year": None,
        "description": "Document processed for RAG",
        "categories": []  
    }
    
    # Try to load from config file
    config_file = os.path.join(os.path.dirname(os.path.dirname(__file__)), "data", "metadata.json")
    
    if os.path.exists(config_file):
        try:
            with open(config_file, 'r', encoding='utf-8') as f:
                config = json.load(f)
                if filename in config:
                    metadata = default_metadata.copy()
                    metadata.update(config[filename])
                    return metadata
        except Exception as e:
            print(f"Warning: Could not load metadata config: {e}")
    
    return default_metadata


def remove_duplicate_chunks(chunks: List[Document]) -> List[Document]:

    seen = set()
    unique_chunks = []
    
    for chunk in chunks:
        # normalize content before hashing for better deduplication
        normalized_content = " ".join(chunk.page_content.lower().split())
        content_hash = get_chunk_hash(normalized_content)
        
        if content_hash not in seen:
            seen.add(content_hash)
            unique_chunks.append(chunk)
    
    print(f"Removed {len(chunks) - len(unique_chunks)} duplicates. {len(unique_chunks)} chunks remain.")
    return unique_chunks


def detect_language(text: str, default_language: str = "en") -> str:
   
    if not text or len(text.strip()) < 10:
        return default_language
    
    try:
        # uses the first 300 chars for quicker detection
        detected_lang = detect(text[:300])
        return detected_lang
    except LangDetectException:
        # if detection fails 
        return default_language
    except Exception as e:
        print(f"Warning: Language detection error: {e}")
        return default_language
    
def setup_logger(name: str, level: int = logging.INFO) -> logging.Logger:

    logger = logging.getLogger(name)
    logger.setLevel(level)
    
    if not logger.handlers:
        handler = logging.StreamHandler()
        formatter = logging.Formatter(
            fmt='%(asctime)s | %(name)-20s | %(levelname)-8s | %(message)s',
            datefmt='%Y-%m-%d %H:%M:%S'
        )
        handler.setFormatter(formatter)
        logger.addHandler(handler)
    
    return logger

